# -*- coding: utf-8 -*-
"""SAMR-Bert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JKHClovDOR1zsJLyZRz3OT2d61c4IEg8
"""

!pip3 install ktrain

import os.path
import numpy as np
import tensorflow as tf
import ktrain
import pandas as pd
from ktrain import text
import zipfile

zip = zipfile.ZipFile('train.tsv.zip')
zip.extractall()

zip = zipfile.ZipFile('test.tsv.zip')
zip.extractall()

df_train=pd.read_csv('train.tsv',sep='\t',nrows=2500)
df_train=df_train.dropna(how='any')
df_train=df_train.drop(columns=['PhraseId','SentenceId'])
df_train

df['Sentiment'].unique()

(x_train, y_train), (x_test, y_test), preproc =  text.texts_from_df(train_df=df_train,text_column='Phrase',label_columns ='Sentiment',val_df=df_train,maxlen=400,preprocess_mode='bert')

model = text.text_classifier(name='bert',
                             train_data=(x_train, y_train),
                             preproc=preproc)

learner = ktrain.get_learner(model=model,
                             train_data=(x_train, y_train),
                             val_data=(x_test, y_test),
                             batch_size=6)

learner.fit_onecycle(lr=2e-5,
                     epochs=1)